movie/movie_review/api/urls.py
from django.urls import path
from api import views

app_name = 'api'
urlpatterns = [
    # 映画
    path('v1/movies/', views.movie_list, name='movie_list'),   # 一覧
]

movie/movie_review/cms/urls.py
from django.urls import path
from cms import views

app_name = 'cms'
urlpatterns = [
    # 映画
    path('movie/', views.movie_list, name='movie_list'),   # 一覧
    path('movie/add/', views.movie_edit, name='movie_add'),  # 登録
    path('movie/mod/<int:movie_id>/', views.movie_edit, name='movie_mod'),  # 修正
    path('movie/del/<int:movie_id>/', views.movie_del, name='movie_del'),   # 削除
    # 感想
    path('impression/<int:movie_id>/', views.ImpressionList.as_view(), name='impression_list'),  # 一覧
    path('impression/add/<int:movie_id>/', views.impression_edit, name='impression_add'),        # 登録
    path('impression/mod/<int:movie_id>/<int:impression_id>/', views.impression_edit, name='impression_mod'),  # 修正
    path('impression/del/<int:movie_id>/<int:impression_id>/', views.impression_del, name='impression_del'),   # 削除
]

movie/movie_review/movie_review/urls.py
from django.contrib import admin
from django.urls import path, include   # ←, includeを追加

urlpatterns = [
    path('cms/', include('cms.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

movie/movie_review/api/models.py
from django.db import models

# Create your models here.

movie/movie_review/cms/models.py
from django.db import models


class Movie(models.Model):
    """作品"""
    name = models.CharField('作品名', max_length=255)
    company = models.CharField('配給会社', max_length=255, blank=True)
    time = models.IntegerField('上映時間', blank=True, default=0)

    def __str__(self):
        return self.name


class Impression(models.Model):
    """感想"""
    movie = models.ForeignKey(Movie, verbose_name='作品', related_name='impressions', on_delete=models.CASCADE)
    comment = models.TextField('コメント', blank=True)

    def __str__(self):
        return self.comment

movie/movie_review/cms/forms.py
from django.forms import ModelForm
from cms.models import Movie, Impression


class MovieForm(ModelForm):
    """映画のフォーム"""

    class Meta:
        model = Movie
        fields = ('name', 'company', 'time',)


class ImpressionForm(ModelForm):
    """感想のフォーム"""

    class Meta:
        model = Impression
        fields = ('comment',)

movie/movie_review/api/views.py
import json
from collections import OrderedDict
from django.http import HttpResponse
from cms.models import Movie


def render_json_response(request, data, status=None):
    """response を JSON で返却"""
    json_str = json.dumps(data, ensure_ascii=False, indent=2)
    callback = request.GET.get('callback')
    if not callback:
        callback = request.POST.get('callback')  # POSTでJSONPの場合
    if callback:
        json_str = "%s(%s)" % (callback, json_str)
        response = HttpResponse(json_str, content_type='application/javascript; charset=UTF-8', status=status)
    else:
        response = HttpResponse(json_str, content_type='application/json; charset=UTF-8', status=status)
    return response


def movie_list(request):
    """映画と感想のJSONを返す"""
    movies = []
    for movie in Movie.objects.all().order_by('id'):

        impressions = []
        for impression in movie.impressions.order_by('id'):
            impression_dict = OrderedDict([
                ('id', impression.id),
                ('comment', impression.comment),
            ])
            impressions.append(impression_dict)

        movie_dict = OrderedDict([
            ('id', movie.id),
            ('name', movie.name),
            ('company', movie.company),
            ('time', movie.time),
            ('impressions', impressions)
        ])
        movies.append(movie_dict)

    data = OrderedDict([ ('movies', movies) ])
    return render_json_response(request, data)

movie/movie_review/cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from cms.models import Movie, Impression
from cms.forms import MovieForm, ImpressionForm
from django.views.generic.list import ListView


def movie_list(request):
    """映画の一覧"""
    # return HttpResponse('映画の一覧')
    movies = Movie.objects.all().order_by('id')
    return render(request,
                  'cms/movie_list.html',  # 使用するテンプレート
                  {'movies': movies})  # テンプレートに渡すデータ


def movie_edit(request, movie_id=None):
    """映画の編集"""
    # return HttpResponse('映画の編集')
    if movie_id:  # movie_id が指定されている (修正時)
        movie = get_object_or_404(Movie, pk=movie_id)
    else:  # movie_id が指定されていない (追加時)
        movie = Movie()

    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)  # POST された request データからフォームを作成
        if form.is_valid():  # フォームのバリデーション
            movie = form.save(commit=False)
            movie.save()
            return redirect('cms:movie_list')
    else:  # GET の時
        form = MovieForm(instance=movie)  # movie インスタンスからフォームを作成

    return render(request, 'cms/movie_edit.html', dict(form=form, movie_id=movie_id))


def movie_del(request, movie_id):
    """映画の削除"""
    # return HttpResponse('映画の削除')
    movie = get_object_or_404(Movie, pk=movie_id)
    movie.delete()
    return redirect('cms:movie_list')


class ImpressionList(ListView):
    """感想の一覧"""
    context_object_name = 'impressions'
    template_name = 'cms/impression_list.html'
    paginate_by = 2  # １ページは最大2件ずつでページングする

    def get(self, request, *args, **kwargs):
        movie = get_object_or_404(Movie, pk=kwargs['movie_id'])  # 親の映画を読む
        impressions = movie.impressions.all().order_by('id')  # 映画の子供の、感想を読む
        self.object_list = impressions

        context = self.get_context_data(object_list=self.object_list, movie=movie)
        return self.render_to_response(context)


def impression_edit(request, movie_id, impression_id=None):
    """感想の編集"""
    movie = get_object_or_404(Movie, pk=movie_id)  # 親の映画を読む
    if impression_id:  # impression_id が指定されている (修正時)
        impression = get_object_or_404(Impression, pk=impression_id)
    else:  # impression_id が指定されていない (追加時)
        impression = Impression()

    if request.method == 'POST':
        form = ImpressionForm(request.POST, instance=impression)  # POST された request データからフォームを作成
        if form.is_valid():  # フォームのバリデーション
            impression = form.save(commit=False)
            impression.movie = movie  # この感想の、親の映画をセット
            impression.save()
            return redirect('cms:impression_list', movie_id=movie_id)
    else:  # GET の時
        form = ImpressionForm(instance=impression)  # impression インスタンスからフォームを作成

    return render(request,
                  'cms/impression_edit.html',
                  dict(form=form, movie_id=movie_id, impression_id=impression_id))


def impression_del(request, movie_id, impression_id):
    """感想の削除"""
    impression = get_object_or_404(Impression, pk=impression_id)
    impression.delete()
    return redirect('cms:impression_list', movie_id=movie_id)

movie/movie_review/cms/templates/cms/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'cms/js/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

movie/movie_review/cms/templates/cms/impression_edit.html
{% extends "cms/base.html" %}
{% load bootstrap4 %}

{% block title %}感想の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">感想の編集</h4>
    {% if impression_id %}
    <form action="{% url 'cms:impression_mod' movie_id=movie_id impression_id=impression_id %}" method="post">
    {% else %}
    <form action="{% url 'cms:impression_add' movie_id=movie_id %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:impression_list' movie_id=movie_id %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

movie/movie_review/cms/templates/cms/impression_list.html
{% extends "cms/base.html" %}

{% block title %}感想の一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">感想の一覧 <small class="text-muted ml-3">{{ movie.name }}</small></h4>
    <a href="{% url 'cms:impression_add' movie_id=movie.id %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>コメント</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for impression in impressions %}
            <tr>
                <td>{{ impression.id }}</td>
                <td>{{ impression.comment|linebreaksbr }}</td>
                <td>
                    <a href="{% url 'cms:impression_mod' movie_id=movie.id impression_id=impression.id %}"
                       class="btn btn-outline-primary btn-sm">修正</a>
                    <a href="#" class="btn btn-outline-danger btn-sm del_confirm"
                       data-pk="{{ impression.id }}"
                       data-url="{% url 'cms:impression_del' movie_id=movie.id impression_id=impression.id %}">削除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                             aria-label="Previous"><span aria-hidden="true">&laquo;</span><span
                            class="sr-only">Previous</span></a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span
                            aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
                {% endif %}
                {% for linkpage in page_obj.paginator.page_range %}
                    {% if linkpage == page_obj.number %}
                        <li class="page-item active"><a class="page-link" href="#">{{ linkpage }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ linkpage }}">{{ linkpage }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                             aria-label="Next"><span aria-hidden="true">&raquo;</span><span
                            class="sr-only">Next</span></a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span
                            aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

    <a href="{% url 'cms:movie_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{# 削除確認モーダルダイアログ #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">確認</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>ID: <span id="del_pk"></span> を削除しますか？</p>
            </div>
            <div class="modal-footer">
                <form method="POST" id="delete-form">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">OK</button>
                </form>
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="$('#deleteModal').modal('hide')">Cancel</button>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block extra_js %}
    <script>
        $(function () {
            $('.del_confirm').on('click', function () {
                var pk = $(this).data("pk");
                var url = $(this).data("url");
                $("#del_pk").text(pk);
                $('#delete-form').attr('action', url);
                $('#deleteModal').modal('show');
            });
        });
    </script>
{% endblock %}

movie/movie_review/cms/templates/cms/movie_edit.html
{% extends "cms/base.html" %}
{% load bootstrap4 %}

{% block title %}映画の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">映画の編集</h4>
    {% if movie_id %}
    <form action="{% url 'cms:movie_mod' movie_id=movie_id %}" method="post">
    {% else %}
    <form action="{% url 'cms:movie_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:movie_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

movie/movie_review/cms/templates/cms/movie_list.html
{% extends "cms/base.html" %}

{% block title %}映画の一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">映画の一覧</h4>
    <a href="{% url 'cms:movie_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">作品名</th>
            <th scope="col">配給会社</th>
            <th scope="col">時間</th>
            <th scope="col">操作</th>
        </tr>
        </thead>
        <tbody>
        {% for movie in movies %}
            <tr>
                <th scope="row">{{ movie.id }}</th>
                <td>{{ movie.name }}</td>
                <td>{{ movie.company }}</td>
                <td>{{ movie.time }}</td>
                <td>
                    <a href="{% url 'cms:movie_mod' movie_id=movie.id %}"
                       class="btn btn-outline-primary btn-sm">修正</a>
                    <a href="{% url 'cms:movie_del' movie_id=movie.id %}" class="btn btn-outline-danger btn-sm">削除</a>
                    <a href="{% url 'cms:impression_list' movie_id=movie.id %}"
                       class="btn btn-outline-info btn-sm">感想の一覧</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}